### ISSUE TITLE
More intelligent handling of `package.json`.

### ISSUE THREAD

**Issue by rwjblue** [kellyselden/ember-cli-update#68]
After running ember-cli-update on ~ 25 or so  addons (and learning how to use `git mergetool`) I've found that fixing up the merge conflicts in `package.json` end up being the most time consuming.  I think we can do even better than `git` for this specific file.

In general, I'd like to:

1. Run [sort-package-json](https://github.com/keithamus/sort-package-json) (to ensure the correct sort order before applying).
2. Leverage [three-way-merger](https://github.com/bantic/three-way-merger) to update the specific `dependencies` / `devDependencies` required. 
3. Generate a patch of the `package.json` files (using `--from` and `--to` versions) excluding changes in `dependencies` and `devDependencies` using [RFC6902](https://www.npmjs.com/package/rfc6902) and apply them.

**Comment by rwjblue** [comment]
What do you think @kellyselden?  I could try to implement behind a flag (e.g. make it opt-in) then we can see how we like it...

**Comment by kellyselden** [comment]
Sounds like a great idea! We could even ask @seawatts or @san650 if they want to help contribute the node console GUI option selection workflow.

**Comment by rwjblue** [comment]
I started working on this in https://github.com/kellyselden/ember-cli-update/pull/70.

**Comment by san650** [comment]
@rwjblue we did that for [ember-cli-updater](https://github.com/mvdwg/ember-cli-updater). You can take a look at https://github.com/mvdwg/ember-cli-updater/blob/51a5923b276b9e2e9c3788b64c08b0a4bd98b14f/lib/updater.js

There's one corner case we came across when implementing this, if the user _edits_ a dependency that comes with ember-cli to pin a specific version we need to ask the user what to do. This is because  we don't know what the user tried to fix by doing that, sometimes you want to pin a dependency to fix an issue with other libraries.

I don't think its useful to have three addons that try to fix the same issue, so let me know if I can be of help by focusing on making this addon the one that fixes the issue once and for all, I'll deprecate ember-cli-updater in favor of this one once we have this feature merged.

Thanks @kellyselden and @rwjblue for working on this problem, upgrading addons have been a pain for me for a long time now.

**Comment by rwjblue** [comment]
Totally agreed that we should consolidate efforts.  TBH, I wasn't aware of the other addons (there's also `ember-cli-commands`) when @kellyselden first mentioned this repo to me.

**Comment by rwjblue** [comment]
@kellyselden - I think the longer term goal here (for all of us) is to have a much more intelligent upgrade process be the default for ember-cli. We should probably make an issue here to discuss with all relevant parties about how best to consolidate efforts.

**Comment by san650** [comment]
@kategengler commented on slack the other day that she was working on a RFC proposal for ember-cli to tackle this feature. I'm not sure what's the status of that but I think these addons help to validate ideas so no effort is wasted here.

IMHO seeing so many people worried and working on this problem makes me think we need to start aligning these efforts.

cc/ @rwjblue @kellyselden @seawatts

**Comment by kategengler** [comment]
I think the hope is that this addon eventually becomes part of ember-cli by default.

**Comment by seawatts** [comment]
Yeah, `ember-cli-commands` already does a pretty good job at this using the three way merger. It would be nice to somehow combine these projects
